# Generated by Django 5.0.3 on 2024-04-10 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmsapp', '0012_student_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_notification',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmsapp.student'),
        ),
    ]
