# Generated by Django 5.0.3 on 2024-04-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmsapp', '0018_alter_attendance_report_attendance_id_studentreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentReport',
            new_name='StudentResult',
        ),
    ]
