# Generated by Django 5.0.3 on 2024-04-11 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmsapp', '0019_rename_studentreport_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
