# Generated by Django 5.0.3 on 2024-05-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmsapp', '0020_attendance_attendance_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance_report',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
